/**
 * Placeholder data for Timelines SEIA component
 */

export const placeholderData = {
    episodes: [
        'tiempo_entre_presentacion_icsara',
        'tiempo_entre_icsara_adenda',
        'tiempo_entre_adenda_icsara_complementario',
        'tiempo_entre_icsara_complementario_adenda_complementaria',
        'tiempo_entre_adenda_complementaria_ice',
        'tiempo_entre_ice_rca',
        'tiempo_hasta_presentacion_icsara',
        'tiempo_hasta_icsara_adenda',
        'tiempo_hasta_adenda_icsara_complementario',
        'tiempo_hasta_icsara_complementario_adenda_complementaria',
        'tiempo_hasta_adenda_complementaria_ice',
        'tiempo_hasta_ice_rca'
    ],
    data: [
        {
            tipo_ingreso_seia: 'DIA',
            region: 'Interregional',
            tipologia_letra: 'b',
            tipologia: 'b1',
            etiqueta_inversion: 'Pequeños (0 - 10)',
            expediente_presentacion: '2003-01-01',
            tiempo_entre_presentacion_icsara: 41.0,
            tiempo_entre_icsara_adenda: 22.0,
            tiempo_entre_adenda_icsara_complementario: null,
            tiempo_entre_icsara_complementario_adenda_complementaria: null,
            tiempo_entre_adenda_complementaria_ice: null,
            tiempo_entre_ice_rca: 11.0,
            tiempo_hasta_presentacion_icsara: 41.0,
            tiempo_hasta_icsara_adenda: 63.0,
            tiempo_hasta_adenda_icsara_complementario: null,
            tiempo_hasta_icsara_complementario_adenda_complementaria: null,
            tiempo_hasta_adenda_complementaria_ice: 101.0,
            tiempo_hasta_ice_rca: 112.0
        },
        {
            tipo_ingreso_seia: 'DIA',
            region: 'Interregional',
            tipologia_letra: 'b',
            tipologia: 'b1',
            etiqueta_inversion: 'Pequeños (0 - 10)',
            expediente_presentacion: '2005-01-01',
            tiempo_entre_presentacion_icsara: 25.0,
            tiempo_entre_icsara_adenda: 8.0,
            tiempo_entre_adenda_icsara_complementario: 7.0,
            tiempo_entre_icsara_complementario_adenda_complementaria: null,
            tiempo_entre_adenda_complementaria_ice: null,
            tiempo_entre_ice_rca: 1.0,
            tiempo_hasta_presentacion_icsara: 25.0,
            tiempo_hasta_icsara_adenda: 33.0,
            tiempo_hasta_adenda_icsara_complementario: 50.0,
            tiempo_hasta_icsara_complementario_adenda_complementaria: null,
            tiempo_hasta_adenda_complementaria_ice: 70.0,
            tiempo_hasta_ice_rca: 71.0
        },
        {
            tipo_ingreso_seia: 'DIA',
            region: 'Metropolitana',
            tipologia_letra: 'c',
            tipologia: 'c2',
            etiqueta_inversion: 'Medianos (10 - 50)',
            expediente_presentacion: '2008-01-01',
            tiempo_entre_presentacion_icsara: 35.0,
            tiempo_entre_icsara_adenda: 15.0,
            tiempo_entre_adenda_icsara_complementario: 12.0,
            tiempo_entre_icsara_complementario_adenda_complementaria: 18.0,
            tiempo_entre_adenda_complementaria_ice: 25.0,
            tiempo_entre_ice_rca: 8.0,
            tiempo_hasta_presentacion_icsara: 35.0,
            tiempo_hasta_icsara_adenda: 50.0,
            tiempo_hasta_adenda_icsara_complementario: 62.0,
            tiempo_hasta_icsara_complementario_adenda_complementaria: 80.0,
            tiempo_hasta_adenda_complementaria_ice: 105.0,
            tiempo_hasta_ice_rca: 113.0
        },
        {
            tipo_ingreso_seia: 'EIA',
            region: 'Valparaíso',
            tipologia_letra: 'a',
            tipologia: 'a1',
            etiqueta_inversion: 'Grandes (≥ 100)',
            expediente_presentacion: '2010-01-01',
            tiempo_entre_presentacion_icsara: 52.0,
            tiempo_entre_icsara_adenda: 28.0,
            tiempo_entre_adenda_icsara_complementario: 15.0,
            tiempo_entre_icsara_complementario_adenda_complementaria: 22.0,
            tiempo_entre_adenda_complementaria_ice: 30.0,
            tiempo_entre_ice_rca: 12.0,
            tiempo_hasta_presentacion_icsara: 52.0,
            tiempo_hasta_icsara_adenda: 80.0,
            tiempo_hasta_adenda_icsara_complementario: 95.0,
            tiempo_hasta_icsara_complementario_adenda_complementaria: 117.0,
            tiempo_hasta_adenda_complementaria_ice: 147.0,
            tiempo_hasta_ice_rca: 159.0
        },
        {
            tipo_ingreso_seia: 'DIA',
            region: 'Biobío',
            tipologia_letra: 'b',
            tipologia: 'b2',
            etiqueta_inversion: 'Pequeños (0 - 10)',
            expediente_presentacion: '2013-01-01',
            tiempo_entre_presentacion_icsara: 30.0,
            tiempo_entre_icsara_adenda: 12.0,
            tiempo_entre_adenda_icsara_complementario: null,
            tiempo_entre_icsara_complementario_adenda_complementaria: null,
            tiempo_entre_adenda_complementaria_ice: null,
            tiempo_entre_ice_rca: 9.0,
            tiempo_hasta_presentacion_icsara: 30.0,
            tiempo_hasta_icsara_adenda: 42.0,
            tiempo_hasta_adenda_icsara_complementario: null,
            tiempo_hasta_icsara_complementario_adenda_complementaria: null,
            tiempo_hasta_adenda_complementaria_ice: 78.0,
            tiempo_hasta_ice_rca: 87.0
        },
        {
            tipo_ingreso_seia: 'EIA',
            region: 'Antofagasta',
            tipologia_letra: 'c',
            tipologia: 'c1',
            etiqueta_inversion: 'Grandes (≥ 100)',
            expediente_presentacion: '2015-01-01',
            tiempo_entre_presentacion_icsara: 48.0,
            tiempo_entre_icsara_adenda: 25.0,
            tiempo_entre_adenda_icsara_complementario: 18.0,
            tiempo_entre_icsara_complementario_adenda_complementaria: 20.0,
            tiempo_entre_adenda_complementaria_ice: 28.0,
            tiempo_entre_ice_rca: 10.0,
            tiempo_hasta_presentacion_icsara: 48.0,
            tiempo_hasta_icsara_adenda: 73.0,
            tiempo_hasta_adenda_icsara_complementario: 91.0,
            tiempo_hasta_icsara_complementario_adenda_complementaria: 111.0,
            tiempo_hasta_adenda_complementaria_ice: 139.0,
            tiempo_hasta_ice_rca: 149.0
        },
        {
            tipo_ingreso_seia: 'DIA',
            region: 'Los Lagos',
            tipologia_letra: 'a',
            tipologia: 'a2',
            etiqueta_inversion: 'Medianos (10 - 50)',
            expediente_presentacion: '2018-01-01',
            tiempo_entre_presentacion_icsara: 38.0,
            tiempo_entre_icsara_adenda: 18.0,
            tiempo_entre_adenda_icsara_complementario: 10.0,
            tiempo_entre_icsara_complementario_adenda_complementaria: null,
            tiempo_entre_adenda_complementaria_ice: null,
            tiempo_entre_ice_rca: 7.0,
            tiempo_hasta_presentacion_icsara: 38.0,
            tiempo_hasta_icsara_adenda: 56.0,
            tiempo_hasta_adenda_icsara_complementario: 66.0,
            tiempo_hasta_icsara_complementario_adenda_complementaria: null,
            tiempo_hasta_adenda_complementaria_ice: 92.0,
            tiempo_hasta_ice_rca: 99.0
        },
        {
            tipo_ingreso_seia: 'EIA',
            region: 'Interregional',
            tipologia_letra: 'c',
            tipologia: 'c3',
            etiqueta_inversion: 'Grandes (≥ 100)',
            expediente_presentacion: '2020-01-01',
            tiempo_entre_presentacion_icsara: 55.0,
            tiempo_entre_icsara_adenda: 32.0,
            tiempo_entre_adenda_icsara_complementario: 20.0,
            tiempo_entre_icsara_complementario_adenda_complementaria: 25.0,
            tiempo_entre_adenda_complementaria_ice: 35.0,
            tiempo_entre_ice_rca: 15.0,
            tiempo_hasta_presentacion_icsara: 55.0,
            tiempo_hasta_icsara_adenda: 87.0,
            tiempo_hasta_adenda_icsara_complementario: 107.0,
            tiempo_hasta_icsara_complementario_adenda_complementaria: 132.0,
            tiempo_hasta_adenda_complementaria_ice: 167.0,
            tiempo_hasta_ice_rca: 182.0
        },
        {
            tipo_ingreso_seia: 'DIA',
            region: 'Maule',
            tipologia_letra: 'b',
            tipologia: 'b1',
            etiqueta_inversion: 'Pequeños (0 - 10)',
            expediente_presentacion: '2021-01-01',
            tiempo_entre_presentacion_icsara: 28.0,
            tiempo_entre_icsara_adenda: 10.0,
            tiempo_entre_adenda_icsara_complementario: 8.0,
            tiempo_entre_icsara_complementario_adenda_complementaria: null,
            tiempo_entre_adenda_complementaria_ice: null,
            tiempo_entre_ice_rca: 6.0,
            tiempo_hasta_presentacion_icsara: 28.0,
            tiempo_hasta_icsara_adenda: 38.0,
            tiempo_hasta_adenda_icsara_complementario: 46.0,
            tiempo_hasta_icsara_complementario_adenda_complementaria: null,
            tiempo_hasta_adenda_complementaria_ice: 65.0,
            tiempo_hasta_ice_rca: 71.0
        },
        {
            tipo_ingreso_seia: 'EIA',
            region: 'Coquimbo',
            tipologia_letra: 'a',
            tipologia: 'a1',
            etiqueta_inversion: 'Medianos (10 - 50)',
            expediente_presentacion: '2022-01-01',
            tiempo_entre_presentacion_icsara: 42.0,
            tiempo_entre_icsara_adenda: 22.0,
            tiempo_entre_adenda_icsara_complementario: 14.0,
            tiempo_entre_icsara_complementario_adenda_complementaria: 19.0,
            tiempo_entre_adenda_complementaria_ice: 26.0,
            tiempo_entre_ice_rca: 11.0,
            tiempo_hasta_presentacion_icsara: 42.0,
            tiempo_hasta_icsara_adenda: 64.0,
            tiempo_hasta_adenda_icsara_complementario: 78.0,
            tiempo_hasta_icsara_complementario_adenda_complementaria: 97.0,
            tiempo_hasta_adenda_complementaria_ice: 123.0,
            tiempo_hasta_ice_rca: 134.0
        }
    ]
};
